project_id = "puejfjhrinmsjvisyomh"

[functions.google-auth]
verify_jwt = false

[functions.google-callback]
verify_jwt = false

[functions.google-calendar-events]
verify_jwt = false

[functions.google-calendar-billing]
verify_jwt = false

[functions.google-calendar-update-colors]
verify_jwt = false

[functions.green-invoice-webhook]
verify_jwt = false
